apiVersion: v1 
kind: Service
metadata:
    name: shortbreadService
    labels: 
        app: my-nginx
spec:
    ports:
      - port: 443
        protocol: TCP
    selector: 
      app: nginx
    type: LoadBalancer